Repository CodingTestStudy2/Daily_Morning_Coding_Test, pull requests merged in 2025-08, with the labels that each got.

#1378 [노형민] Day05
  leetcode2/1easy/노형민/Q1592.cs
  leetcode2/2medium/노형민/Q1376.cs
Labels: #2 성공, #1 성공, #3 실패, Lang: C/C++/C#

#1376 [최원준] Day05
  leetcode2/1easy/최원준/Q1592.java
  leetcode2/2medium/최원준/Q1376.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#1379 [최원준] Day06
  leetcode2/2medium/최원준/Q1048.java
  leetcode2/2medium/최원준/Q300.java
  leetcode2/2medium/최원준/Q673.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#1386 [노형민] Day07
  leetcode2/1easy/노형민/Q3477.cs
  leetcode2/2medium/노형민/Q307.cs
Labels: #2 성공, #1 성공, #3 실패, Lang: C/C++/C#

#1385 [최은서] Day07
  leetcode2/1easy/최은서/Q3477.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#1384 [조은비] Day07
  leetcode2/1easy/조은비/3477.py
  leetcode2/2medium/조은비/307.py
Labels: #1 성공, #3 실패, #2 실패, Lang: Python

#1383 [최원준] Day07
  leetcode2/1easy/최원준/Q3477_2.java
  leetcode2/2medium/최원준/Q307.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#1391 [김도연] Day08
  leetcode2/2medium/김도연/Q3291.java
  leetcode2/2medium/김도연/Q3479.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#1390 [최은서] Day08
  leetcode2/2medium/최은서/Q729.js
Labels: #3 성공, #2 실패, #1 실패, Lang: JavaScript

#1388 [최원준] Day08
  leetcode2/2medium/최원준/Q3479.java
  leetcode2/2medium/최원준/Q729.java
Labels: #2 성공, #3 성공, #1 실패, Lang: Java/Kotlin

#1387 [조은비] Day08
  leetcode2/2medium/조은비/3291.py
Labels: #3 실패, #2 실패, #1 실패, Lang: Python

#1396 [최은서] Day09
  leetcode2/1easy/최은서/Q1317.js
  leetcode2/2medium/최은서/Q2750.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#1395 [노형민] Day09
  leetcode2/1easy/노형민/Q1317.cs
  leetcode2/2medium/노형민/Q2750.cs
Labels: #2 성공, #1 성공, #3 실패, Lang: C/C++/C#

#1393 [김도연] Day09
  leetcode2/1easy/김도연/Q1317.java
  leetcode2/2medium/김도연/Q1357.java
  leetcode2/2medium/김도연/Q2750.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#1398 [최원준] Day10
  leetcode2/2medium/최원준/Q2396.java
  leetcode2/2medium/최원준/Q3035.java
Labels: #3 성공, #1 성공, #2 실패, Lang: Java/Kotlin

#1403 [최은서] Day11
  leetcode2/1easy/최은서/Q3633.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#1402 [노형민] Day11
  leetcode2/1easy/노형민/Q3633.cs
  leetcode2/2medium/노형민/Q808.cs
Labels: #2 성공, #1 성공, #3 실패, Lang: C/C++/C#

#1401 [최원준] Day11
  leetcode2/1easy/최원준/Q3633.java
  leetcode2/2medium/최원준/Q808.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#1409 [김도연] Day12
  leetcode2/2medium/김도연/Q2981.java
  leetcode2/2medium/김도연/Q973.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#1410 [최은서] Day13
  leetcode2/1easy/최은서/Q2913.js
  leetcode2/2medium/최은서/Q2476.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#1414 [노형민] Day14
  leetcode2/2medium/노형민/Q2105.cs
  leetcode2/2medium/노형민/Q2947.cs
Labels: #2 성공, #1 성공, #3 실패, Lang: C/C++/C#

#1413 [최은서] Day14
  leetcode2/2medium/최은서/Q2105.js
  leetcode2/2medium/최은서/Q2947.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#1419 [최은서] Day15
  leetcode2/1easy/최은서/Q.2614.js
  leetcode2/2medium/최은서/Q274.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#1417 [최원준] Day15
  leetcode2/1easy/최원준/Q2614.java
  leetcode2/2medium/최원준/Q274.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#1423 [조은비] Day17
  leetcode2/1easy/조은비/35365.py
  leetcode2/2medium/조은비/822.py
Labels: #2 성공, #1 성공, #3 실패, Lang: Python

#1422 [최은서] Day17
  leetcode2/1easy/최은서/Q3536.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#1427 [최은서] Day18
  leetcode2/2medium/최은서/Q2012.js
Labels: #2 성공, #3 실패, #1 실패, Lang: JavaScript

#1425 [최원준] Day18
  leetcode2/2medium/최원준/Q1631.java
  leetcode2/2medium/최원준/Q2012.java
  leetcode2/2medium/최원준/Q3576.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#1429 [조은비] Day18
  leetcode2/1easy/조은비/521.py
  leetcode2/2medium/조은비/1218.py
Labels: #1 성공, #3 실패, #2 실패, Lang: Python

#1431 [최은서] Day20
  leetcode2/1easy/최은서/Q2768.js
Labels: #3 성공, #2 실패, #1 실패, Lang: JavaScript

#1432 [최은서] Day01
  leetcode2/1easy/최은서/Q2481.js
  leetcode2/2medium/최은서/Q3584.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#1434 [최은서] Day02
  leetcode2/2medium/최은서/Q1642.js
Labels: #2 성공, #3 실패, #1 실패, Lang: JavaScript

#1437 [최은서] Day03
  leetcode2/1easy/최은서/Q2824.js
  leetcode2/2medium/최은서/Q1353.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#1436 [최원준] Day03
  leetcode2/1easy/최원준/Q2824.java
  leetcode2/2medium/최원준/Q1353.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#1439 [최은서] Day04
  leetcode2/2medium/최은서/Q915.js
Labels: #2 성공, #3 실패, #1 실패, Lang: JavaScript

#1438 [최원준] Day04
  leetcode2/2medium/최원준/Q1774.java
  leetcode2/2medium/최원준/Q1911.java
  leetcode2/2medium/최원준/Q915.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#1441 [최은서] Day05
  leetcode2/1easy/최은서/Q2614.js
  leetcode2/1easy/최은서/Q859.js
  leetcode2/3hard/최은서/Q1793.js
Labels: #3 성공, #1 성공, #2 실패, Lang: JavaScript
