Repository CodingTestStudy2/Daily_Morning_Coding_Test, pull requests merged in 2025-01, with the labels that each got.

#763 [유동하] Day03
  leetcode/1easy/유동하/1566.js
  leetcode/2medium/유동하/787.js
  leetcode/3hard/유동하/2608.js
Labels: #3 실패, #2 실패, #1 실패, Lang: JavaScript

#762 [최원준] Day 03
  leetcode/1easy/최원준/Q1566.java
  leetcode/2medium/최원준/Q787.java
  leetcode/3hard/최원준/Q2608.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#767 [조유리] Day04
  leetcode/1easy/조유리/LC_3010.java
  leetcode/2medium/조유리/LC_1020.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#765 [이현진] Day04
  leetcode/1easy/3010.js
  leetcode/2medium/1020.js
  leetcode/3hard/995.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#772 [최원준] Day 05
  leetcode/1easy/최원준/Q2839.java
  leetcode/3hard/최원준/Q502.java
Labels: #3 성공, #1 성공, #2 실패, Lang: Java/Kotlin

#777 [임강민] Day06
  leetcode/1easy/임강민/1893.py
Labels: #1 성공, #3 실패, #2 실패, Lang: Python

#776 [조유리] DAY06
  leetcode/1easy/조유리/LC_1893.java
  leetcode/3hard/조유리/LC_995.java
  프로그래머스/.DS_Store
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#775 [최원준] Day06
  leetcode/1easy/최원준/Q1893.java
  leetcode/2medium/최원준/Q1093.java
  leetcode/3hard/최원준/Q1340.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#774 [ 위성원] Day06
  leetcode/1easy/위성원/1893.js
  leetcode/2medium/위성원/1093.js
Labels: #1 성공, #2 실패, Lang: JavaScript

#773 [유동하] Day06
  leetcode/1easy/유동하/1893.js
  leetcode/2medium/유동하/1093.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#780 [위성원] Day07
  leetcode/1easy/위성원/3136.js
  leetcode/2medium/위성원/462.js
Labels: #2 성공, #1 성공, Lang: JavaScript

#779 [조유리] DAY07
  leetcode/1easy/조유리/LC_3136.java
  leetcode/2medium/조유리/LC_462.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#778 [최원준] Day 07
  leetcode/1easy/최원준/Q3136.java
  leetcode/2medium/최원준/Q462.java
  leetcode/3hard/최원준/Q3414.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#786 [유동하] Day08
  leetcode/1easy/유동하/2833.js
  leetcode/2medium/유동하/1519.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#785 [오하늘] Day08
  leetcode/1easy/오하늘/2833.py
  leetcode/2medium/오하늘/1519.py
Labels: #1 성공, #3 실패, #2 실패, Lang: Python

#783 [최원준]Day08
  leetcode/1easy/최원준/Q2833.java
  leetcode/2medium/최원준/Q1519.java
  leetcode/3hard/최원준/Q793.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#790 [위성원] Day09
  leetcode/1easy/위성원/1486.js
  leetcode/2medium/위성원/1882.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#789 [이현진] Day09
  leetcode/1easy/1486.js
  leetcode/2medium/1882.js
  leetcode/3hard/2344.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#788 [조유리] DAY09
  leetcode/1easy/조유리/LC_1486.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#787 [최원준]Day09
  leetcode/1easy/최원준/Q1486.java
  leetcode/2medium/최원준/Q1882.java
  leetcode/3hard/최원준/Q2344.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#795 [이현진] Day 10
  leetcode/1easy/766.js
  leetcode/2medium/2707.js
  leetcode/3hard/3017.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#794 [조유리] DAY10
  leetcode/1easy/조유리/LC_766.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#793 [오하늘] Day10
  leetcode/1easy/오하늘/766.py
  leetcode/2medium/오하늘/2707.py
Labels: #1 성공, #3 실패, #2 실패, Lang: Python

#792 [최원준]Day10
  leetcode/1easy/최원준/Q766.java
  leetcode/2medium/최원준/Q2707.java
  leetcode/3hard/최원준/Q3017.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#791 [위성원] Day10
  leetcode/1easy/위성원/766.js
  leetcode/2medium/위성원/2027.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#804 [김혜연] DAY11
  .DS_Store
  leetcode/1easy/김혜연/1961.py
  leetcode/2medium/김혜연/1432.py
Labels: #2 성공, #1 성공, #3 실패, Lang: Python

#803 [오하늘] Day11
  leetcode/1easy/오하늘/1961.py
  leetcode/2medium/오하늘/1432.py
Labels: #1 성공, #3 실패, #2 실패, Lang: Python

#802 [조유리] DAY11
  leetcode/1easy/조유리/LC_1961.java
  leetcode/2medium/조유리/LC_1432.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#801 [이현진] Day11
  leetcode/1easy/1961.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#800 [권민서] Day1
  leetcode/1easy/권민서/1961.java
  leetcode/2medium/권민서/1432.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#798 [위성원] Day11
  leetcode/1easy/위성원/1961.js
  leetcode/2medium/위성원/1432.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#797 [최원준] Day11
  leetcode/1easy/최원준/Q1961.java
  leetcode/2medium/최원준/Q1432.java
  leetcode/3hard/최원준/Q1639.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#796 [유동하] Day11
  leetcode/1easy/유동하/1961.js
  leetcode/2medium/유동하/1432.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#809 [권민서] Day2
  leetcode/1easy/권민서/1784.java
  leetcode/2medium/권민서/863.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#808 [유동하] Day12
  leetcode/1easy/유동하/1784.js
  leetcode/2medium/유동하/863.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#807 [위성원] Day12
  leetcode/1easy/위성원/1784.js
  leetcode/2medium/위성원/863.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#806 [최원준] Day12
  leetcode/1easy/최원준/Q1784.java
  leetcode/2medium/최원준/Q863.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#805 [임강민] Day11
  leetcode/1easy/임강민/1784.py
Labels: #1 성공, #3 실패, #2 실패, Lang: Python

#816 [권민서] Day3
  leetcode/1easy/권민서/3258.java
  leetcode/2medium/권민서/1856.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#817 [오하늘] Day13
  leetcode/1easy/오하늘/3258.py
  leetcode/2medium/오하늘/1856.py
Labels: #3 실패, #2 실패, #1 실패, Lang: Python

#815 [이현진] Day13
  leetcode/1easy/3258.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#814 [조유리] DAY13
  leetcode/1easy/조유리/LC_3258.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#813 [위성원] Day13
  leetcode/1easy/위성원/3258.js
  leetcode/2medium/위성원/1856.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#812 [김혜연] Day13
  leetcode/1easy/김혜연/3258.py
Labels: #1 성공, #3 실패, #2 실패, Lang: Python

#811 [최원준] Day13
  leetcode/1easy/최원준/Q3258.java
  leetcode/2medium/최원준/Q1856.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#810 [유동하] Day13
  leetcode/1easy/유동하/3258.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#822 [위성원] Day14
  leetcode/1easy/위성원/1582.js
  leetcode/2medium/위성원/2271.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#821 [권민서] Day4
  leetcode/1easy/권민서/1582.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#820 [박은비] Day14
  leetcode/1easy/박은비/1582.swift
Labels: #1 성공, #3 실패, #2 실패, Lang: Swift

#819 [최원준] Day14
  leetcode/1easy/최원준/Q1582.java
  leetcode/3hard/최원준/Q1627.java
Labels: #3 성공, #1 성공, #2 실패, Lang: Java/Kotlin

#818 [이현진] Day14
  leetcode/1easy/1582.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#825 [김혜연] Day15
  leetcode/1easy/김혜연/3110.c++
  leetcode/2medium/김혜연/3365.py
Labels: #2 성공, #1 성공, #3 실패, Lang: Python, Lang: C/C++

#824 [박은비] Day15
  leetcode/1easy/박은비/3120.swift
  leetcode/2medium/박은비/3365.swift
Labels: #1 성공, #3 실패, #2 실패, Lang: Swift

#823 [최원준] Day15
  leetcode/1easy/최원준/Q3120.java
  leetcode/2medium/최원준/Q3365.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#829 [이현진] Day 16
  leetcode/1easy/이현진/3407.js
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#828 [최원준] Day16
  leetcode/1easy/최원준/Q3407.java
  leetcode/2medium/최원준/Q2039.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#827 [박은비] Day16
  leetcode/1easy/박은비/3407.swift
Labels: #1 성공, #3 실패, #2 실패, Lang: Swift

#835 [이경호] Day17
  leetcode/1easy/이경호/3289.cpp
Labels: #1 성공, #3 실패, #2 실패, Lang: C/C++

#834 [조유리] Day17
  leetcode/1easy/조유리/LC_3289.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#833 [최원준] Day17
  leetcode/1easy/최원준/Q3289.java
  leetcode/2medium/최원준/Q2831.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#840 [조유리] Day18
  leetcode/1easy/조유리/LC_2733.java
  leetcode/2medium/조유리/LC_2380.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#838 [위성원] Day18
  leetcode/1easy/위성원/2733.js
  leetcode/2medium/위성원/2382.js
  leetcode/3hard/위성원/879.js
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#837 [최원준] Day18
  leetcode/1easy/최원준/Q2733.java
  leetcode/2medium/최원준/Q2380.java
  leetcode/3hard/최원준/Q879.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#836 [이경호] Day18
  leetcode/1easy/이경호/2733.cpp
  leetcode/2medium/이경호/2380.cpp
Labels: #2 성공, #1 성공, #3 실패, Lang: C/C++

#844 [조유리] Day19
  leetcode/1easy/조유리/LC_1656.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#843 [이경호] Day19
  leetcode/1easy/이경호/1656.cpp
Labels: #1 성공, #3 실패, #2 실패, Lang: C/C++

#842 [위성원] Day19
  leetcode/1easy/위성원/1656.ts
  leetcode/2medium/위성원/1927.ts
Labels: #1 성공, #3 실패, #2 실패, Lang: JavaScript

#841 [최원준] Day19
  leetcode/1easy/최원준/Q1656.java
Labels: #1 성공, #3 실패, #2 실패, Lang: Java/Kotlin

#848 [이경호] Day 20
  leetcode/1easy/이경호/2062.cpp
Labels: #1 성공, #3 실패, #2 실패, Lang: C/C++

#847 [최원준] Day20
  leetcode/1easy/최원준/Q2062.java
  leetcode/2medium/최원준/Q365.java
  leetcode/3hard/최원준/Q2246.java
Labels: #2 성공, #3 성공, #1 성공, Lang: Java/Kotlin

#846 [위성원] Day20
  leetcode/1easy/위성원/2062.ts
  leetcode/2medium/위성원/365.ts
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript

#849 [이경호] Day21
  leetcode/1easy/이경호/2965.cpp
Labels: #1 성공, #3 실패, #2 실패, Lang: C/C++

#854 [최원준] Day22
  leetcode/1easy/최원준/Q2409.java
  leetcode/2medium/최원준/Q2284.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#853 [오하늘] Day22
  leetcode/1easy/오하늘/2409.py
Labels: #1 성공, #3 실패, #2 실패, Lang: Python

#852 [조유리] Day22
  leetcode/1easy/조유리/LC_2409.java
  leetcode/2medium/조유리/LC_1901.java
  leetcode/2medium/조유리/LC_2284.java
Labels: #2 성공, #1 성공, #3 실패, Lang: Java/Kotlin

#851 [박은비] Day22
  leetcode/2medium/박은비/2284.swift
Labels: #2 성공, #3 실패, #1 실패, Lang: Swift

#850 [위성원] Day22
  leetcode/1easy/위성원/2409.ts
  leetcode/2medium/위성원/2284.ts
Labels: #2 성공, #1 성공, #3 실패, Lang: JavaScript
